org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
forge_version=47.4.20
forge_version_range=[47.1.0,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=farmersrespite
mod_name=Farmer's Respite
mod_license=MIT License
mod_version=2.1.2
mod_group_id=umpaz.farmersrespite
mod_authors=Umpaz, Probleyes
mod_credits=Umpaz, Probleyes, SoyTutta
mod_description=An addon for the Farmer's Delight mod centered around brewing tea and coffee in the kettle

craftorio_version=2

jei_version=15.20.0.130
farmersdelight_version=4638874
