modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="farmersrespite"
version="${version}"
displayName="Farmer's Respite"
# updateJSONURL=""
logoFile="logo.png"
logoBlur=false
credits="Umpaz, Probleyes, SoyTutta"
authors="Umpaz, Probleyes"
description="An addon for the Farmer's Delight mod centered around brewing tea and coffee in the kettle"
itemIcon="farmersrespite:kettle"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.farmersrespite]]
    modId="forge"
    mandatory=true
versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersrespite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersrespite]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="NONE"
    side="BOTH"
